---
title: "HW4: Screencast"
author: "Thibault"
date: "7 May 2018"
output: html_document

---

* Create a __two minute screencast with narration__ showing what 
you did for HW3 with some slides.
* Upload the video to an online video-platform such as YouTube or Vimeo.
* Use your groupXYZ_2018_hw4's Github repository to upload
    * the slides (PDF or HTML formats, no Powerpoint/Keynote files), 
    * the Rmarkdown file that you used to generate the slides 
    (if you choose to use the concepts presented April 30th), 
    * and a README file (txt format) with the link to the video.

Please make sure that:

* The sound quality of your video is good. 
* You are not running longer than 2 minutes (we will strictly enforce the time limit).
* You use principles of good storytelling and presentations to get your key points across. 
* You focus the majority of your screencast on your main contributions rather than on technical details:
    * Make sure the main contributions are upfront and center rather than at the end.
    * What insights did you gain? 
    * What is the single most important thing you would like your audience to take away? 

Information about how to prepare these screencasts can be found [here](https://docs.google.com/document/d/1alPLuBOW5YPoQDa57KZes1h72PoQDoDj21-UEKOHp1I/pub). 