---
title: "HW2: Wrangling, Visualization and Modeling"
author: "Thibault"
date: "26 March 2018"
output: html_document

---

[Download the HW2 skeleton files](https://raw.githubusercontent.com/tvatter/dsfba_2018/master/data/dsfba_homework2_skeleton.zip). To successfully complete the first assignment you
will have to do the following:

1. Create a new project with the name `homework2.Rproj`.
2. Organize the files in the right folders to provide ease of building a final
`hw2_report.Rmd` = `hw1_ex1.Rmd` + `hw1_ex2.Rmd`.
3. Following the instructions below, complete missing code in chunks in `hw1_ex1.Rmd` and `hw1_ex2.Rmd`. 


To obtain the maximum number of points, use whenever possible:

* the pipeline symbol %>%,
* `dplyr` verbs,
* `kable` to print tables,
* `ggplot` to produce the figures,
* `broom` to format the results model fits.

Also, pay attention to the general aesthetics of your report (i.e., formatting of 
the tables, digits of precision, sizing of the figures). Use inline code 
to display single numbers, and `echo = FALSE` for code chunks when you display 
a table of produce a figure.
