---
title: "HW3: Many models"
author: "Thibault"
date: "30 April 2018"
output: html_document

---

[Download the HW3 skeleton files](https://raw.githubusercontent.com/tvatter/dsfba_2018/master/data/dsfba_homework3_skeleton.zip). To successfully complete the first assignment you
will have to do the following:

1. Create a new project with the name `homework3.Rproj`.
2. Organize the files in the right folders to provide ease of building a final report.
3. Following the instructions below, complete missing code in chunks in `hw3_report.Rmd`. 

To obtain the maximum number of points, use whenever possible:

* the pipeline symbol %>%,
* `dplyr` verbs,
* `kable` to print tables,
* `ggplot` to produce the figures,
* `purr`'s functions to minimize code duplication,
* `broom`'s functions to format the results model fits.

Also: 

* Pay attention to the general aesthetics of your report (i.e., formatting of 
the tables, sizing of the figures, etc.). 
* Use inline code to display single numbers, and `echo = FALSE` for code chunks when you display 
a table of produce a figure (i.e., we don't want to see code unless it is necessary).
* Minimize the amount of code duplication by using iterations concepts and list-columns.
* Comment your code to explain what you are doing.

## Solutions for HW3

The [solutions for HW3 are available here](https://raw.githubusercontent.com/tvatter/dsfba_2018/master/data/dsfba_homework3_solution.zip).
Please note that this is only a minimum draft version and should not to be taken as an example of "perfect submission". 
Other working solutions will be graded accordingly. 

